/**
 * @fileoverview Cloudflare Workers entry point (Wrapper Pattern)
 *
 * This file handles Hono API routes and Tail events, and delegates
 * all frontend UI rendering to the compiled Astro SSR worker.
 */
import type { ExportedHandler, ExecutionContext, TraceItem } from "@cloudflare/workers-types";

import { app as honoApp } from "./backend/api/index";
import { processTailEvents } from "./backend/services/tailHandler";

// @ts-ignore - This file is generated by Astro during the build process
import astroApp from "../dist/_worker.js/index.js";

const handler: ExportedHandler<Env> = {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // 1. Handle API and Documentation routes via Hono
    if (
      url.pathname.startsWith("/api/") ||
      url.pathname === "/openapi.json" ||
      url.pathname === "/swagger" ||
      url.pathname === "/scalar" ||
      url.pathname === "/docs"
    ) {
      return honoApp.fetch(request as any, env, ctx);
    }

    // 2. Delegate everything else to the Astro SSR handler
    if (astroApp && typeof astroApp.fetch === "function") {
      return astroApp.fetch(request as any, env, ctx);
    } else if (astroApp && (astroApp as any).default && typeof (astroApp as any).default.fetch === "function") {
      return (astroApp as any).default.fetch(request as any, env, ctx);
    }

    return new Response("Astro SSR build not found", { status: 500 });
  },

  async tail(events: TraceItem[], env: Env, ctx: ExecutionContext) {
    await processTailEvents(events, env, ctx);
  },
};

export default handler;

// Explicitly export Durable Objects required by Cloudflare
export { LogAnalyzerAgent } from "./backend/agent";
export { LogStreamer } from "./backend/do/LogStreamer";
